### ISSUE TITLE
Docker discussion

### ISSUE THREAD

**Issue by cloudrac3r** [cloudrac3r/bibliogram#81]
As of 64ab9cfcee1d207d32b6b76fbfe85b0e6aa6bb7f, we now have dockerfiles. I am not experienced with Docker, so some things are probably not optimal.

Feel free to use this thread to talk about things related to Bibliogram and Docker.

**Comment by cloudrac3r** [comment]
> ...unless they need to run some update script on the database or something, which would then need additional instructions.

Database upgrades are handled automatically when Bibliogram starts, so this should already be fine.

**Comment by giocomai** [comment]
Brief comments on the above:

- yes, docker-compose is basically just a different way to run docker, so you don't need to build anything separate for docker

- if you want an utomatic update, I'd probably add the call to `docker pull username/bibliogram` in the crontab (it would download when a new version is found), and then force a restart of the docker-compose. This may also depend on the exact setups. More experienced docker users may have more streamlined solutions.

**Comment by kalak-sudo** [comment]
I have done [this](https://github.com/cloudrac3r/bibliogram/pull/76#issuecomment-645973754) with a .dockerignore and now everything works perfect :)

EXCEPT one thing:

How could we achieve SSL with this docker image @giocomai ?  I have tried doing [this](https://codefresh.io/docker-tutorial/using-docker-generate-ssl-certificates/) and [this](https://stackoverflow.com/questions/26028971/docker-container-ssl-certificates) with no luck.

**Comment by cloudrac3r** [comment]
Try running nginx with certs from letsencrypt? https://github.com/cloudrac3r/bibliogram/wiki/Installing#configuring-https

**Comment by giocomai** [comment]
It depends a bit on how you run your server. My take is that using `traefik` is the easiest way to add docker services to a server, if you only use docker containers on that server.

So here's a full `docker-compose.yml` that uses traefik to manage https certificates (and, in principle, load balancing and all sort of nifty things), especially if you run multiple services from the same server... beyond bibliogram, you can add other services, and as long as there is an A redirect to that server's IP, traefik will automatically manage all redirects, get and renew certificates and serve them correctly. Just change *all* instances of example.com to your domain/email/etc.. 

If you have other non-docker services running from the same server, then you'd need to figure out things via reverse proxy (e.g. with nginx), and take it from there, perhaps share the `.letsencrypt` certifcate via volume, or...  well, this is how however a rather different conversation. 

A solution such as the one below, plus something that keeps bibliogram updated (probably, a script run daily via crontab), would make having a new instance up and running really easy. 

A final note: do not rely on my Docker build, I may not keep it updated, either build your own, or use the official one when it's out. 


```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.myhttpchallenge.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myhttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myhttpchallenge.acme.email=email@example.com"
      - "--certificatesresolvers.myhttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
        network1:
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"  
  
  bibliogram:
    image: giocomai/bibliogram:latest
    networks:
      network1:
    volumes:
      - ./bibliogram/config.js:/app/config.js:ro
      - bibliogram_db:/db
    ports:
      - "10407:10407"
    restart:
      unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=10407"
      - "traefik.http.routers.bibliogram.rule=Host(`bibliogram.example.com`)"
      - "traefik.http.routers.bibliogram.entrypoints=websecure"
      - "traefik.http.routers.bibliogram.tls.certresolver=myhttpchallenge"
      - "traefik.docker.network=network1" 
      
volumes:
  bibliogram_db:
  
  
networks:
  network1:
    external: true
```
